### PR TITLE
Urban opt50

### PR DESCRIPTION
**Pull request by brianlball**

### CODE REVIEW

**Comment by nllong** [comment]
Nice! I'll take a look at this early next week!

**Comment by tijcolem** [comment]
@brianlball Can you merge in the latest develop branch? We enabled Github actions and disabled Travis. You can add all the algo tests in now as we have more run time allotted.

**Comment by brianlball** [comment]
@tijcolem merged in develop, green.  this still ran the tests in this dir, correct? https://github.com/NREL/OpenStudio-server/tree/develop/server/spec/features

**Review by nllong — APPROVED** [review]
Looks great! I'll merge as soon as the tests pass.

**Comment by nllong** [comment]
> @tijcolem merged in develop, green. this still ran the tests in this dir, correct? https://github.com/NREL/OpenStudio-server/tree/develop/server/spec/features

Looks like the urbanopt tests run within docker! Should be good to go. I have one more tweak that I'm going to commit.

image

**Comment by brianlball** [comment]
Damn thats a beautiful sight....

**Comment by nllong** [comment]
I have one last commit that is nothing more than a couple typos... then I'll merge down.

**Pull request merged**
