### PR TITLE
update plots with display name choices

### PR DESCRIPTION
**Pull request by brianlball**
https://github.com/NREL/OpenStudio-server/issues/321

make display name a choice option on the parallel coords and x-y plots.

### CODE REVIEW

**Comment by brianlball** [comment]
there are drop down boxes on parallelcoordinate and x-y plots.  the results also change on the parallelcoordinate plots as well.

**Comment by brianlball** [comment]
@DavidGoldwasser will this address https://github.com/NREL/OpenStudio-server/issues/321?

**Review by kflemin — APPROVED** [review]
this looks great! i added axis labels but if you don't like them, just revert! :)

**Comment by kflemin** [comment]
@brianlball, I also fixed a bug about the display name selector drop-down not using the variable tied to the model to populate the dropdown (the 'selected' one). I also reworked the display name selector on the parallel coords page to make it smaller (to the side of the variables section). I'm assuming users would have already selected what they want display-wise on the xy plot page and wouldn't need to mess with it too much on this page.
Screen Shot 2022-05-18 at 1 44 10 PM

**Review by DavidGoldwasser — APPROVED** [review]

**Pull request merged**
