### PR TITLE
Update mongo and redis

### PR DESCRIPTION
**Pull request by tijcolem**
Updates mongo and redis to use the latest supported versions. Sets a user-defined password for Mongo and Redis.  

Current server mongo::3.4.10
Latest mongo: 4.4.2

Current server redis: 4.0.6
Latest redis: 6.09

This should get updated as well: https://github.com/NREL/OpenStudio-PAT/issues/173

### CODE REVIEW

**Review by nllong — APPROVED** [review]
These changes look great! If the tests pass then we should be good. 

I tested locally with docker-compose and PAT3.1. Old db volumes will need to be deleted, but I think that is a given and not an issue due to the ephemeral running of the server.

**Comment by nllong** [comment]
@tijcolem Can you add a note in the CHANGELOG on what has been updated? Thanks! 🤘

**Comment by tijcolem** [comment]
Thanks, @nllong  I added notes to CHANGELOG. All up-to-date.

**Comment by nllong** [comment]
@tijcolem -- do we need to migrate to travis-ci.com? Or do we have adequate testing with Jenkins across the platforms?

https://travis-ci.org/github/NREL/OpenStudio-server/builds/751822545

Also, the failure looks like failed resolution to some gems. That may resolve itself...

**Comment by tijcolem** [comment]
@nllong  Yeah, we have some Travis changes ahead. As you pointed out, they are decommissioning https://travis-ci.org/. (no cutoff date posted).  Once we are on travis-ci.com, they also will begin charging for MacOs builds using a credit system.  You can read more here: 
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

My understanding is once we are moved off https://travis-ci.org these changes will take effect, so we'll need to plan now. I'll look into this more and find out options.

**Comment by tijcolem** [comment]
And oh, I actually canceled the Travis runs as this was just a document update.

**Comment by nllong** [comment]
Gotcha, thanks for the update on Travis. On other projects we have been moving over to github actions and it has been nice. I've yet to setup mac builds on github actions... maybe that is an option?

**Comment by tijcolem** [comment]
GitHub actions is great. I've used that for some jobs on OpenStudio. The only potential concern is the lack of disk space - 14 GB which may be an issue for our integration runs.  https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

**Pull request merged**
