### PR TITLE
Dockerize pat

### PR DESCRIPTION
**Pull request by rHorsey**
Support for PAT. @nllong please review prior to merge.

### CODE REVIEW

**Comment by nllong** [comment]
I assume we aren't going to merge this until the tests pass, right?

**Comment by nllong** [comment]
in general this looks good. It looks like we have yet to implement calling the CLI to run the simulations... can you verify that this feature is still lacking @henryHorsey?

**Comment by rHorsey** [comment]
The CLI isn't invoked yet here. That work lives at present in the https://github.com/NREL/OpenStudio-server/tree/dockerize-osw
Currently, the reason there are no tests is because I enabled circleci testing but haven't added in any dockerize tests. I tried adding in vagrant tests, but rsync isn't enabled on circleci.

**Comment by rHorsey** [comment]
Also worth noting that the cli integration has been customized to use the jsons, not the xmls, to avoid the previous issue regarding the class-name tag in legacy xmls.

**Comment by macumber** [comment]
Measure jsons?  Once you have the CLI, you can use it to force update the measures to have xmls with class name in them.

**Comment by rHorsey** [comment]
That's exactly the feature we were missing a month or two ago.

**Pull request merged**
