### PR TITLE
Fix cancel

### LINKED ISSUE #437: cancel run does not work anymore
run any of the SEB examples and try and cancel the run.

### PR DESCRIPTION
**Pull request by anyaelena**
Fixes #437

### CODE REVIEW

**Comment by nllong** [comment]
> One of the travis test failures is an actual issue. I'll look into it.

@anyaelena -- actually is there a way you can fix the test?

**Comment by anyaelena** [comment]
@nllong yes, i'll look into it.

**Comment by nllong** [comment]
@anyaelena thanks. I think this can be merged down once you fix the failing test.

**Comment by anyaelena** [comment]
@nllong  i verified locally that complete is working as expected.  i don't have the test working but my working theory is that the introduction of the [after_enqueue hook](https://github.com/NREL/OpenStudio-server/blob/fix-cancel/server/app/jobs/resque_jobs/run_simulate_data_point.rb#L42) is messing with the test setup.

**Comment by nllong** [comment]
@anyaelena - i fixed the test to have it check for something else to ensure completion. I'm pretty sure that the queue is not getting updated because the simulations are not actually running in a queue so any triggers are probably ignored. (https://github.com/NREL/OpenStudio-server/pull/463/files#diff-0a351848e90287c4b763ccbc56e78ea3R143).

**Pull request merged**
