### PR TITLE
Two analyses at a time

### PR DESCRIPTION
**Pull request by brianlball**
https://github.com/NREL/OpenStudio-server/issues/717
https://github.com/NREL/OpenStudio-server/issues/753

Running 2 analyses Resque queues in the web-background container can cause out of order ResqueJobs::RunAnalysis jobs. 
For example, when an LHS analysis is submitted to OSAF, it is actually two jobs.  The first is `analysis_type='lhs'` followed by `analysis_type='batch_run'`. see [batch_run_methods](https://github.com/NREL/OpenStudio-analysis-gem/blob/develop/lib/openstudio/analysis/server_api.rb#L14). They are both [Resque.enqueue](https://github.com/NREL/OpenStudio-server/blob/requeue/server/app/models/analysis.rb#L121)'d right after each other, but there are no [hooks ](https://github.com/NREL/OpenStudio-server/blob/requeue/server/app/jobs/resque_jobs/run_analysis.rb#L12) or requirements that one goes before the other. With only 1 [Resque Worker](https://github.com/NREL/OpenStudio-server/blob/requeue/docker/server/start-web-background.sh#L9) in the [web-background](https://github.com/NREL/OpenStudio-server/blob/develop/docker-compose.deploy.yml#L52) container, only one job in the analyses queue is run at a time, the first being the non-`batch_run` `analysis_type`.

If there are 2 Resque workers in the web-background container, either by changing [start-web-background.sh](https://github.com/NREL/OpenStudio-server/blob/requeue/docker/server/start-web-background.sh#L9) or [helm-chart](https://github.com/NREL/openstudio-server-helm/blob/develop/openstudio-server/values.yaml#L118), `batch_run.perform` can start before `lhs.perform` can complete which results in datapoints trying to be run before they are made.

This is how it should work, where `LHS generates the datapoints` and `batch_run` then `data_point.submit_simulation`:

orig_order

VS

This is what can happen with 2 analysis queues right now, `batch_run` has no datapoints to submit because `lhs` has not created them yet:

2wb_order

### CODE REVIEW

**Comment by brianlball** [comment]
image

**Comment by brianlball** [comment]
parallel analyses with the new [test](https://github.com/NREL/OpenStudio-server/blob/two_analyses/server/spec/features/docker_stack_requeue_spec.rb#L259)

image

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio-server/issues/618

**Review by nllong — APPROVED** [review]
wow, this is fancy! Good work figuring out and fixing!

**Pull request merged**
