### PR TITLE
Travis build artifacts

### PR DESCRIPTION
**Pull request by anyaelena**
Updates:
1) Update both Linux and OSX environments to use Ruby built with --enable-load-relative flag.  
2) Add "publish" job types that export build *.tar.gz to S3.  These are in the openstudio-server-artifacts bucket and set to private by default.

Caveats: 
1) These builds haven't been tested/confirmed to work with PAT.  If they don't and you want to pursue this path while i'm on leave, the relevant files are ci/travis/setup.sh for the details of Ruby build and ci/travis/export_install_* for the export command and upload.  Some AWS credentials are stored in Travis.
2) The actual directory structure within the openstudio-server-artifacts bucket is wonky - :/full/path/from/host/machine. I didn't have a chance to tune this.
3) Note that you cannot, to my knowledge, get a Travis build without rvm installed and that rvm stomps on any number of environment variables, including when you `cd` and when a new script is run.  This is why i'm setting env variables explicitly at the start of each script.  This could be improved.

### CODE REVIEW

**Comment by anyaelena** [comment]
Closes #509

**Comment by nllong** [comment]
Thanks for getting this to work! Code looks good.

Are we planning on moving this over to Jenkins or are we going to keep the travis up-and-running?

**Comment by anyaelena** [comment]
No immediate plans to migrate this to Jenkins. We were on the fence for a while but internal osx resources are already strained.

**Comment by nllong** [comment]
Okay, thanks @anyaelena. Do we have a timeline to get these into PAT for full integration testing?

**Comment by tijcolem** [comment]
This looks good. Nice work @anyaelena!  I just put in another pr #512 to bump to OpenStudio 2.9.0-rc1 so this would be a good time to test the build artifacts with OpenStudio Installer package 2.9.0-rc1. 

I could also rebuild the 2.8.1 OpenStudio installer with these build artifacts and test, but that may not be necessary if 2.9.0 works fine. Let me see if I can put in a pr to branch `travis_build_artifacts` and then try out build artifacts in the 2.9.0 installer before we hit merge.

**Comment by tijcolem** [comment]
I tried using the OpenStudio 2.9.0 osx server build artifact using the result from #513 but I encountered errors when starting up the local OpenStudio-server via PAT. This is the error when running server manually vs running in PAT (it's the same command that is spawned from PAT). 

`$ openstudio_meta start_local --worker-number=11 --energyplus-exe-path=/Users/tcoleman/OpenStudio/test/ParametricAnalysisTool.app/Contents/Resources/EnergyPlus/energyplus --openstudio-exe-path=/Users/tcoleman/OpenStudio/test/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio --ruby-lib-path=/Users/tcoleman/OpenStudio/test/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/Ruby --mongo-dir=/Users/tcoleman/OpenStudio/test/ParametricAnalysisTool.app/Contents/Resources/mongo/bin --debug /Users/tcoleman/git/OpenStudio-PAT/sample_projects/Office_HVAC`

```
/Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find nokogiri-1.6.8.1 in any of the sources (Bundler::GemNotFound)
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `map!'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `materialize'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:170:in `specs'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:237:in `specs_for'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/definition.rb:226:in `requested_specs'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/runtime.rb:20:in `setup'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler.rb:107:in `setup'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/bundler-1.17.1/lib/bundler/setup.rb:20:in `<top (required)>'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Applications/OpenStudio-2.9.0/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

We may need to download the pre-built ruby as part of the CI process that is known to work and use that ruby to build Openstudio-server packages vs building ruby with rvm with configure flags.  https://github.com/NREL/OpenStudio-PAT/wiki/Pat-Build-Notes

**Pull request closed without merging**
