### PR TITLE
2.6.1 (needs version notes in README)

### PR DESCRIPTION
**Pull request by anyaelena**

### CODE REVIEW

**Comment by anyaelena** [comment]
@rHorsey @nllong the travis fail is due to docker 2.6.1 image not pushed - working on that in other repo.  could one of you add version notes if applicable? Anything else to do here?

**Comment by anyaelena** [comment]
@nllong @rHorsey are we good to merge this?  will one of you add version notes?

**Comment by nllong** [comment]
I updated the change log. I also added the release instructions (https://github.com/NREL/OpenStudio-server/blob/c1f9702a74dd8847328a04219aa4a994a6b0d012/lib/release_instructions.md). 

I would like to get the analysis init and final scripts into this release... is that possible?

**Comment by anyaelena** [comment]
Yes, i'm planning to merge that branch today .  note that the `scripts` PAT branch should be merged  at same time.

**Comment by anyaelena** [comment]
can we go ahead and merge this?

**Comment by nllong** [comment]
we are going to need new 2.6.1 packages with the updated standards for gbxml... so I say hold off.

**Comment by anyaelena** [comment]
Ok.  Although i did merge this already into my Analysis Finalization Scripts branch.

**Comment by nllong** [comment]
Ok. Merge down then. Just hold off merging to master.

**Pull request merged**
