### PR TITLE
OpenStudio CLI

### LINKED ISSUE #269: Migrate to the openstudio CLI
This is required to support custom gems on the server. Currently the workflow gem is used, see https://github.com/NREL/OpenStudio-server/blob/develop/server/app/workers/run_simulate_data_point.rb#L169-L183. This needs to be replaced with a well mannaged spawned process with identical output log name and file structure. I'd recommend starting with https://github.com/NREL/OpenStudio-server/blob/develop/bin/resources/local.rb#L252-L271 and adapting appropriately. Of particular note, we probably shouldn't timeout the call.

### PR DESCRIPTION
**Pull request by anyaelena**
Closes #269

### CODE REVIEW

**Comment by anyaelena** [comment]
Ok.  This passes tests but using absolute paths to openstudio executable on Windows and Mac/Linux.  On Windows, I think that I can remove this if we assume that openstudio.exe is in PATH (it wasn't for Appveyor setup).  On Mac, we hit [this](https://github.com/NREL/OpenStudio/issues/2911) issue without full path to executable (but may be fixed in newer OS versions?)

Are we even ok with assuming that the openstudio executable is always in PATH?

**Comment by anyaelena** [comment]
Also, per @nllong's comment on the related issue, i've set this to timeout after 2 hours.

**Comment by rHorsey** [comment]
@anyaelena Will this be fixed with the closure of https://github.com/NREL/OpenStudio/issues/2911 ? If so, I'm happy to wait for OS 2.5.1 to be released & then rerun the tests & merge then if you are. Maybe also @macumber

**Comment by rHorsey** [comment]
Sorry - I can't help myself. I really love labels in github. I don't really know why.

**Comment by anyaelena** [comment]
@rHorsey I had to hardcode path to executable in for Windows as well, which is not a known OS bug. 
 I assume this is because the executable directory C:\projects\openstudio\bin was not in PATH.  and then i also assume that is was not in PATH because calling openstudio via workflow gem leaned on [this](https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio-workflow.rb#L31) which in tern uses the RUBYLIB var (i actually don't see where this is used in the code, but it's clearly needed to point to the os ruby wrapper).

So: 
1. OS will probably remove hardcoded path requirement for Linux/OSX.  
2. updating PATH might remove hardcoded path requirement for Windows.  I can try updating PATH to confirm this.
3. ?? I need someone to talk to me about how PAT/OSS work together so i can understand whether this is well tested with our CI and feel comfortable that requiring a change to PATH won't break this.

**Comment by anyaelena** [comment]
@rHorsey Yes.  I'll take a look.  Is this set anywhere other than environment variables in the various CI config files?

**Comment by anyaelena** [comment]
@rHorsey @macumber I have tested this with 2.5.1.  OSX still requires an absolute path to the openstudio executable.  Linux works fine without.

**Comment by anyaelena** [comment]
@kbenne I have to explicitly add the location of the openstudio executable to PATH for our unit tests using the CLI to pass on OSX.  Per Nick/Ry, this should happen as part of the OpenStudio install process.  Let me know if you need more details.

**Comment by anyaelena** [comment]
@kbenne @macumber still having 'find_energyplus' errors when the executable is called without full path.

OSX seems fixed for 2.6.0.  I didn't test it with 2.5.2.

This was fixed 2.5.1 on Ubuntu but seems to have broken again with 2.5.2 and remained broken for 2.6.0.

To reproduce Ubuntu error, you can check out the 2.6.0 branch of https://github.com/NREL/OpenStudio-cli-demo/tree/2.6.0 (project works for version >= 2.5.1, despite branch name) and run the CLI through Docker. You must have Docker installed.

Runs for 2.5.1.  Fails for 2.5.2, 2.6.0:
````docker run -v $(pwd):/var/simdata/openstudio nrel/openstudio:<version> openstudio run -w v2.6.0/workflow.osw````

Runs for 2.5.1, 2.5.2, 2.6.0
````docker run -v $(pwd):/var/simdata/openstudio nrel/openstudio:<version> /usr/local/bin/openstudio run -w v2.6.0/workflow.osw````

**Comment by macumber** [comment]
I think this will fix it but need to test first....

**Comment by anyaelena** [comment]
@shorowit would like to test this branch

**Comment by rHorsey** [comment]
I'm building an AMI (2.6.1-rc2) off of this tonight so David can beat it up tomorrow with lots of gem switching.

**Comment by rHorsey** [comment]
AMI 2.6.1-cli0 has been built against 43291c4 for testing.

**Comment by rHorsey** [comment]
Handed off to @DavidGoldwasser to test `2.6.1-cli0`

**Comment by DavidGoldwasser** [comment]
I have tested analysis finalization scripts on build of develop branch of PAT and a custom server setup. I was able to read from and write to the database.

**Pull request merged**
