### PR TITLE
Travis build artifacts

### LINKED ISSUE #509: Upload native OSX/Linux builds from Travis to S3

### PR DESCRIPTION
**Pull request by anyaelena**
1. Use portable Ruby downloaded from S3 PAT resources for builds and testing. Implode rvm to achieve some clarity regarding which Ruby is being called.
2. Add testing for xcode 10.2 and 11.4 builds
3. Add publish stage for local Linux and Darwin builds.  These upload to S3 but currently not to the pat-dependencies bucket, so there's still a manual copy step. (Closes #509)
4. Docker testing is turned off for this PR as it is getting a significant upgrade in the test_suite PR #594 
5. fix execjs error finding core libs on Catalina, referenced [here](https://github.com/NREL/OpenStudio-PAT/issues/159).  Execjs will be installed from forked repo until rail/execjs merges fix.

@tijcolem @kbenne will you look at the bundle config change for native gems in openstudio-meta?  libxml-ruby was failing on xcode 10.2 (OSX 10.14).  After a fair amount of experimenting I'm optimistic that I have it right.

### CODE REVIEW

**Comment by anyaelena** [comment]
Before merging will want to re-check the uploaded builds and update the `branch = travis_build_artifacts` for the publish builds.

**Comment by anyaelena** [comment]
uploaded builds:
https://openstudio-server-artifacts.s3.amazonaws.com/%3A/OpenStudio-server-b8e1a97e97-linux.tar.gz
https://openstudio-server-artifacts.s3.amazonaws.com/%3A/OpenStudio-server-b8e1a97e97-darwin.tar.gz

**Comment by anyaelena** [comment]
PAT builds to be tested:
https://openstudio-pat-ci-builds.s3-us-west-2.amazonaws.com/travis_oss_builds/ParametricAnalysisTool-3.0.1-Linux.deb
https://openstudio-pat-ci-builds.s3-us-west-2.amazonaws.com/travis_oss_builds/ParametricAnalysisTool-3.0.1-Darwin.dmg

**Comment by tijcolem** [comment]
I tested:
 https://openstudio-pat-ci-builds.s3-us-west-2.amazonaws.com/travis_oss_builds/ParametricAnalysisTool-3.0.1-Linux.deb (Works runing sample Office_HVAC)

**Comment by anyaelena** [comment]
I tested https://openstudio-pat-ci-builds.s3-us-west-2.amazonaws.com/travis_oss_builds/ParametricAnalysisTool-3.0.1-Darwin.dmg

So we're good to merge?

**Pull request merged**
