### PR TITLE
update PSO

### PR DESCRIPTION
**Pull request by brianlball**
add report interval default to 10 and make arg

issue https://github.com/NREL/OpenStudio-server/issues/580

### CODE REVIEW

**Comment by brianlball** [comment]
This adds PSO enhancement for reporting during iterations.  will report every iteration and is configurable by 'report' algo arg.
updates NRELPSO to latest changes from HydroPSO.  issue https://github.com/NREL/OpenStudio-server/issues/580

These changes need docker-openstudio-r:3.6.1-1 (PR https://github.com/NREL/docker-openstudio-r/pull/8)

makes RServe bandwidth unlimited.
bumps 'Rest-Client' to ~>2.0.1 for smoother datapoint creation (aka, less NAs). potential fix for https://github.com/NREL/OpenStudio-server/issues/337

bumps 'bundler' to 2.1.0

adds 'endpoint_mode: dnsrr' config to Docker Swarm containers with no exposed ports.  This addresses Swarm timeout issue in testing. https://github.com/NREL/OpenStudio-server/issues/582

removed IPVS keepalive and memfix hack since they did not fix the Swarm timeout issue.

**Comment by nllong** [comment]
Did you release a new openstudio-r container yet?

`Service 'rserve' failed to build: manifest for nrel/openstudio-r:3.6.1-1 not found`

**Comment by tijcolem** [comment]
Do we want to tag this branch as an incremental release for OpenStudio-server?  Update these two containers and AMI 

```
nrel/openstudio-server:3.0.1-1
nrel/openstudio-rserve:3.0.1-1
AMI: 3.0.1-1
```
Assuming yes. We'll want to add the version extension in server here: https://github.com/NREL/OpenStudio-server/blob/pso_update/server/app/lib/openstudio_server/version.rb#L37-L40  I can update.

**Comment by tijcolem** [comment]
The osx runs on travis are currently timing out as max length is 50 min. Looks like time is spent here. 
https://travis-ci.org/github/NREL/OpenStudio-server/jobs/707740924#L338-L346 

Not sure why this is timing out as I can easily download this https://sqlite.org/2020/sqlite-autoconf-3320300.tar.gz on my local machine.

**Comment by tijcolem** [comment]
Looks like the issue was due to using an older version of osx 10.12. I bumped to version osx 10.13 (xcode 9.4) and CI is looking healthy again.

**Pull request merged**
