### PR TITLE
2.8.0 Release

### PR DESCRIPTION
**Pull request by anyaelena**

### CODE REVIEW

**Comment by anyaelena** [comment]
@nllong @brianlball @rHorsey No surprises in this PR from develop to master but it's a good point for a sanity check on all recent changes if any/all of you want to take a look as reviewers.  I'm going to merge tomorrow am regardless so i can get the new AMI out.

**Comment by brianlball** [comment]
anything major between this and 2.8.0-rc5?

**Comment by anyaelena** [comment]
@brianlball Nothing at all.  OpenStudio is the same package as rc5 and the 2.8.0-rc5 ami was build off our develop branch which hasn't changed.  So this PR is just merging what was in the 2.8.0-rc5 AMI to our master branch.

**Comment by brianlball** [comment]
sweet.  there was one test on 24A which was successful.  would be good to hit it with some more.

**Pull request merged**
