### PR TITLE
yaml file changes to build server packages for all branches, on Mac a…

### PR DESCRIPTION
**Pull request by evanweaver**
…nd Windows, and upload to S3 bucket "openstudio-builds/CI" with unique naming specifying version and SHA in package names.

### CODE REVIEW

**Comment by nllong** [comment]
Just want to make sure that the SHA is the git commit SHA, correct?

**Comment by evanweaver** [comment]
Yep, that's it.

**Comment by rHorsey** [comment]
@evanweaver You can remove the `--with-test-develop` from the openstudio_meta command. #293 has fixed that issue for me.

**Comment by rHorsey** [comment]
Merging this branch to be even with develop to fix AppVeyor commit testing.

**Comment by rHorsey** [comment]
@evanweaver Do you want to remove those `--with-test-develop` flags before we merge?

**Comment by evanweaver** [comment]
@rHorsey please see my commit from earlier today

**Pull request merged**
